/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 3856M$
 * $Date: 2007-11-27$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		3856
#define SVN_REVSTR	"3856M"
#define SVN_REVDATE	"2007-11-27"
#define SVN_REVSTAMP	20071127L
#define SVN_MODIFIED	1

#endif /* SVNREV_H */
