/* This file was generated by the "svnrev" utility.
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 3706$
 * $Date: 2007-01-29$
 */

#define SVN_REV		3706
#define SVN_REVSTR	"3706"
#define SVN_REVDATE	"2007-01-29"
#define SVN_REVSTAMP	20070129L
