/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 5181$
 * $Date: 2015-01-21$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		5181
#define SVN_REVSTR	"5181"
#define SVN_REVDATE	"2015-01-21"
#define SVN_REVSTAMP	20150121L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
