/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 5689$
 * $Date: 2017-06-05$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		5689
#define SVN_REVSTR	"5689"
#define SVN_REVDATE	"2017-06-05"
#define SVN_REVSTAMP	20170605L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
