/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 4032$
 * $Date: 2008-11-14$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		4032
#define SVN_REVSTR	"4032"
#define SVN_REVDATE	"2008-11-14"
#define SVN_REVSTAMP	20081114L
#define SVN_MODIFIED	0

#endif /* SVNREV_H */
